### ISSUE TITLE
404 when using deferral

### ISSUE THREAD

**Issue by steven10172** [Snazzah/slash-create#127]
I'm trying to use your library (v3.3.0) and everything was working when running it as a discord bot, but as soon as I moved everything into an AWS Lambda that is accessible via API Gateway I'm having issues sending followup and replacement messages via deferral (see code below). In discord the bot shows `This interaction failed` instead of the thinking message.

As part of debugging I attempted to have `run` return just a string instead of using `ctx.defer(false)` and the hook works as expected, but I need to use deferral due to the lengthy computation time required to properly respond. I also attempted to manually GET the webhook endpoint that the PATCH request is sent to, to see the original message (which failed) and I received the following response from discord
```
{
    "message": "Unknown Webhook",
    "code": 10015
}
```

Example code:
```
async run(ctx: CommandContext) {
    console.log('Received voyage');
    if (!ctx.guildID) {
      return 'Voyages are not supported in direct message';
    }

    // It takes a while to login and retrieve sheet info, defer the call as it
    // is unlikely we will consistently respond within 3000ms
    await ctx.defer(false);
    
    return ctx.send(...generateMessages());   
}
```

Lambda Logs:
```
START RequestId: f4383aab-c6c0-4e08-b602-9adcfaa88498 Version: $LATEST
--
2021-09-16T09:00:46.309Z	f4383aab-c6c0-4e08-b602-9adcfaa88498	INFO	Got request
2021-09-16T09:00:47.108Z	f4383aab-c6c0-4e08-b602-9adcfaa88498	INFO	Running command: voyage (XXX, guild XXX)


2021-09-16T09:00:48.733Z	f4383aab-c6c0-4e08-b602-9adcfaa88498	INFO	Request: 
{
    "content": "",
    "embeds": [
        {
            "timestamp": "2021-09-18T06:16:30.067Z",
            "footer": {
                "text": "Next roll available after"
            },
            "author": {
                "name": "Sea Worthy Voyages - No rolls available",
                "icon_url": "https://i.imgur.com/hVTcL4l.png"
            },
            "color": 16711680
        },
        {
            "timestamp": "2021-09-18T06:16:30.067Z",
            "footer": {
                "text": "Next roll available after",
                "icon_url": "https://i.imgur.com/hVTcL4l.png"
            },
            "thumbnail": {
                "url": "https://i.imgur.com/lgtKWy4.png"
            },
            "author": {
                "name": "Sea Worthy Voyages - Easy Task",
                "icon_url": "https://i.imgur.com/hVTcL4l.png"
            },
            "color": 12050893,
            "description": "Advance your skills as a lumberjack by Chopping 135 Oak or Willow logs. Post screenshot proof, with timestamp, in the appropriate text channel. If a main account show history proving you didn't buy the product.\n\nYou can complete this task at any time, however; you will not be able to roll another task until 7 days from now",
            "title": "Lumberjack Apprentice"
        }
    ],
    "allowed_mentions": {
        "parse": [
            "roles",
            "users"
        ]
    }
}



2021-09-16T09:00:48.786Z	f4383aab-c6c0-4e08-b602-9adcfaa88498	INFO	 1631782848734 /webhooks/XXX/:token/messages/@original 404: 245ms (474ms avg) \| 1/1 left \| Reset 1631782848734 (0ms left)
--
END RequestId: f4383aab-c6c0-4e08-b602-9adcfaa88498
```

**Comment by Snazzah** [comment]
For starters, I would suggest updating to the latest version of slash-create, but I'd assume this is because the way AWS handles serverless functions rather than a library issue. When it comes to serverless functions, it only really supports giving initial responses and not really on deferring and doing follow-ups. It might be better to set up a webserver instead.

**Comment by steven10172** [comment]
Do you happen to have documentation around what might be the problem that
lambda cannot handle with deferral properly? As long as a message is being
sent the follow-up should be able to replace that and it looks like the
appropriate HTTP calls were made. Maybe the deferral come how failed, I was
unable to properly step through that logic during my limited session.

I plan on upgrading to the newest version and diving deeper into the
problem this weekend, so any resources on specifics to check would be
appreciated.

**Comment by Snazzah** [comment]
I don't have documentation for this. I'm assuming after the initial HTTP response from the interaction that AWS does *something* to the process that makes it not work properly. I've tried using a serverless solution and had problems with deferring mainly because the service stopped/halted the process after it responded to the interaction API request. I'd assume that they aren't really build to continue after responding to the HTTP request. I'm not sure exactly what behavior AWS does once it's initial response is given since that would take some testing. It seems like if you are trying to defer and give follow-ups that serverless functions alone won't be able to work.

**Comment by steven10172** [comment]
Do you happen to know if you can acknowledge the interaction via a new HTTP
request, or do you have to respond to the request discord sends?

I know when accepting over the gateway you have to always respond with HTTP
requests, but wasn't sure if this was allowed when using the webhook
pattern.

**Comment by Snazzah** [comment]
You always have to initially respond for the interaction token to be valid for future HTTP calls.

**Comment by EsteFilipe** [comment]
Having the same problem with Lambda. The command fails when using defer.

**Comment by Snazzah** [comment]
Unless you are doing something right after, I'm not sure how *just* deferring would fail the interaction.

**Comment by Snazzah** [comment]
A bit of a stale issue, will close for now.

**Comment by multimeric** [comment]
I'm also hitting this issue, but I have thought about what is actually happening here, and I'm not actually sure it will ever make sense to defer a hook with lambda. The reason being, a lambda or indeed any interaction endpoint does *not* work like a bot does. It works more like a regular web server: it gets sent a request, which is the interaction, and it must send a response back to discord, which has to be a physical HTTP packet. The lambda terminates when it sends the response, and it can't send the response until it terminates, there's no getting around that. So if you choose to defer, then you have chosen for your one HTTP response to be a "defer" message rather than anything useful.

Another way to think about it: a modern async lambda for NodeJS looks like this:

```js
exports.handler = async function(event, context) {
  return context.logStreamName
}
```

This is simply a function. Can this function return multiple times? Of course not. Currently `slash-create` uses the older non-async API for lambda, which is more like:
```js
exports.handler =  function(event, context, callback) {

}
```
But the `callback` is just a utility that simulates the returning of a single promise, so it's subject to the same constraint that we can't call it multiple times. And that's exactly what's happening when we `defer()` and then `sendFollowUp()`.

***

However, I can think of one (somewhat complex) solution for AWS users. You can write a Step Function StateMachine that does exactly this:

* StateMachine is invoked by API gateway in response to the webhook. 
* State 1: we call a lambda that *always* responds with a deferral.
* State 2: we call our long-running process using a StepFunctions integration. In my case this is a DynamoDB query integration
* State 3: we call a second, different lambda, which sends a follow-up response using the database results

This should be a fairly idiomatic AWS architecture, and plus it should fit easily within the free tier because StepFunctions are one of the services they are more generous with (along with Lambda and DynamoDB).

**Comment by multimeric** [comment]
I've had another look through the [API docs](https://discord.com/developers/docs/interactions/receiving-and-responding#receiving-an-interaction), and I believe my understanding is correct. In particular:

> To respond to a gateway Interaction, make a POST request [...] This endpoint is only valid for Interactions received over the gateway. Otherwise, respond to the POST request to issue an initial response.

So for any webhook interactions handler, you only get one response, which can either be a defer or a reply. I would love to see `slash-create` make this distinction clearer, because some of the `Context` methods (like `defer()`) indeed just reply to the HTTP request, while others (like `sendFollowUp()`) make API calls which can be done later. The API currently makes it seem like you can defer and then followUp from a webhook endpoint, but you can't do this.

However I've iterated a bit on my suggestion above, and I've managed to hack together something nicer. Rather than doing what I suggest above, if you can get a copy to the raw gateway data (and believe me `slash-create` does not make this easy, however #245 should make this less ugly), you can re-invoke the current lambda, but with a slightly different event, so that it will run a different code path which sends a follow up instead of deferring. This way you don't need to add any additional AWS resources at all:

```typescript
// Don't actually export the real handler, instead handle with the below function
const server = new AWSLambdaServer({}, "interactions");

creator
    .withServer(server)
    .on('commandInteraction', (interaction, respond, webserverMode) => {
        // Construct a context manually, so we can use it for convenience
        const ctx = new CommandContext(
            creator,
            interaction,
            respond,
            webserverMode
        );
        
        if (globalEvent.headers.I_DEFERRED_THIS) {
            ctx.defer();
            
	    // Indicate this has already been deferred
	    data.headers.I_DEFERRED_THIS = "true";

	    // Start a new lambda
	    new LambdaClient({}).send(new InvokeCommand({
		FunctionName: process.env.AWS_LAMBDA_FUNCTION_NAME,
		InvocationType: InvocationType.Event,
		Payload: Buffer.from(JSON.stringify(data))
	    }));
        } else {
            ctx.sendFollowUp({ some_data });
        }
    });

// Get a copy of the raw gateway event
let globalEvent: APIGatewayProxyEventV2;

export function interactions(event: APIGatewayProxyEventV2, context: Context, callback: APIGatewayProxyCallbackV2){
    // Store a copy of the raw event
    globalEvent = event;
    // @ts-ignore
    server._onRequest(event, context, callback);
}
```

**Comment by ttomasz** [comment]
For reference to whomever tries to implement message deferral on lambda here's how I did it based on helpful tips from thread above: https://github.com/ttomasz/serverless-duckdb-bot/blob/63d1d5c79e4645d1581e4e751cdc16c5c5d47fb8/index.ts#L31-L66

It has its problems as it seems second lambda tries to acknowledge the message that the first lambda acknowledged but with sufficient exception suppression it works :sweat_smile:
