### ISSUE TITLE
Providing Integer value for Number option cause interaction to fail

### ISSUE THREAD

**Issue by KeyboardRage** [Snazzah/slash-create#302]
# Expected
~~Interactions to be ran, for payload not to be rejected as invalid.~~
Providing Integer value in Discord to a NUMBER option should be valid.

# What happens

Some interactions are rejected, because the key is not verified:
```js
const verified = await verifyKey(
	JSON.stringify(treq.body),
	signature,
	timestamp,
	this.options.publicKey as string
);
// returns false
```
[Found here](https://github.com/Snazzah/slash-create/blob/master/src/creator.ts#L618).
If I disable the verification, the interaction succeeds as normal.

# Description
If you use `CommandOptionType.NUMBER` and provide an integer value in the Discord command, the interaction will fail. It will work if you pass a float.

If you change option to `CommandOptionType.INTEGER` and pass an integer, it is valid.

Consider a command with this option.
`/number n:3` - fails
`/number n:3.1` - succeeds
```js
export default class Number extends SlashCommand {
	constructor(creator) {
		super(creator, {
			name: "number",
			description: "Provide a number",
			options: [{
				type: CommandOptionType.NUMBER,
				name: "n",
				description: "The number to provide",
				required: true
			}]
		});
	}

	// ....
}
```

While this command option allows integers.
`/number n:3` - succeeds

```js
export default class Number extends SlashCommand {
	constructor(creator) {
		super(creator, {
			name: "number",
			description: "Provide a number",
			options: [{
				type: CommandOptionType.INTEGER,
				name: "n",
				description: "The number to provide",
				required: true
			}]
		});
	}

	// ....
}
```
~~
# My setup
* using the Fastify server (Fastify version `3.28.0`)
* slash-create version `5.6.0`
* Node version `16.6.1`

**Comment by Snazzah** [comment]
Try setting the `maxSignatureTimestamp` option in the creator to 30000 or a higher number.

**Comment by Snazzah** [comment]
Not really sure how the request isn't being verified since there wasn't any changes to it. Probably double-check the public key was entered in correctly from the application page.

**Comment by KeyboardRage** [comment]
It is working for some commands, but not others. If I change the Options layout, the command will stop being verified. I change it back, and it works again.

I can try setting up some capturing of the data and do some comparisons over the weekend.

**Comment by cernec1999** [comment]
I had the same error using the `AWSLambdaServer`. The issue is with accessing the required headers in [creator.ts](https://github.com/Snazzah/slash-create/blob/master/src/creator.ts#L604). I believe the Discord API recently changed the capitalization of the headers `X-Signature-Ed25519` and `X-Signature-Timestamp`.

Changing these headers fixes the issue. I'll submit a PR to reflect the changes.

Great tool BTW!

**Comment by KeyboardRage** [comment]
@cernec1999 I believe this could be specific to `AWSLambdaServer`.

For me these headers are all lowercase, and yield `undefined` if I match the casing with your commit/Discord docs. I believe the Fastify server normalises headers to lowercase.

I have not yet had the time to dig into the issue.

**Comment by cernec1999** [comment]
@KeyboardRage Huh, that's really bizarre. I can dig into this later. You're right -- the HTTP spec requires that HTTP headers be case insensitive, and `fastify` normalizes them to be lowercase.

**Comment by KeyboardRage** [comment]
I have found the issue. @cernec1999 @Snazzah 

If you use `CommandOptionType.NUMBER` and then provide an integer value to Discord (which is valid), the interaction will not be validated. If you pass a float, it is valid.

If you change it to `CommandOptionType.INTEGER` and then provide integer, it will work.

**Comment by Snazzah** [comment]
I'm going to guess that integers passed as numbers are converted into decimals while the parser puts it back to an integer. If Discord sends `3.0`, it will be converted into `3` but it won't be exact in the JSON payload when it's turned into a string, so that might be the issue.

AWS lambda doesn't parse the body, [so the server implementation does it instead](https://github.com/Snazzah/slash-create/blob/master/src/servers/lambda.ts#L34), you could log the body and verify that to make sure.
