### ISSUE TITLE
SlashCommand.onBlock/onError can return a Message object, for which there is no constructor?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Snazzah/slash-create#34]
Hi there. I'm writing bindings to this library, and as I work through the types, I've come across the oddity described in the title.

See:

- [`SlashCommand.onBlock()`](https://slash-create.js.org/#/docs/main/latest/class/SlashCommand?scrollTo=onBlock)
- [`Message`](https://slash-create.js.org/#/docs/main/latest/class/Message), specifically, the `data` argument
- The `@hidden` [`MessageData`](https://github.com/Snazzah/slash-create/blob/9b3a872a6e4933908d38eb4ebb1b73869b2b676c/src/structures/message.ts#L6-L23)-type

It's clear why that type is hidden; but that leaves there being no obvious way to construct a `Message` type to return from an `onBlock()` handler? Is this intentional? How, within your API, would a user be intended to return a complex message after the onBlock-handler is triggered?

**Comment by Snazzah** [comment]
I should really actually define the return values for `onBlock` and `onError` functions. They don't actually specifically return `Message` objects, but since I didn't define a return value within the file and I am returning with `ctx.send` which *could* return a message, TypeScript says it returns that and so does the documentation. **It actually doesn't matter what `onBlock` and `onError` returns.** I'll make sure to fix that documentation later.

**Comment by ELLIOTTCABLE** [comment]
Fantastic! Thank you!
