### ISSUE TITLE
Ability to customise throttling a bit more

### ISSUE THREAD

**Issue by lewisakura** [Snazzah/slash-create#439]
I'm trying to reduce the amount of state stored by slash-create in memory, and one of the ideas I had was to store throtting information in Redis to be shared across processes since I tend to use the throttling feature often. I did already notice this:
https://github.com/Snazzah/slash-create/blob/66d556cbb5c5b5d3dfa8af9e610709c27e30315c/src/command.ts#L237-L258
...but because it's private, I assumed we're not really meant to be overriding this (though I don't quite see why not).

What'd be the best approach to add custom throttling logic? Would this require a new feature to be implemented?

**Comment by Snazzah** [comment]
I really should change that to be more customizable since:
1. It's not async (and won't be ran asynchronously in command execution atm)
2. [The throttle object is being changed after returning it](https://github.com/Snazzah/slash-create/blob/66d556cbb5c5b5d3dfa8af9e610709c27e30315c/src/creator.ts#L730), since it assumes its using that same map every command has.

You can pretty much just overwrite this function as long as it returns a ThrottleObject or a null, but also make sure that the usages in the throttle objects can be overwritten. I should've probably gotten that changed by now but it's not too terrible to use.

**Comment by lewisakura** [comment]
> 2. [The throttle object is being changed after returning it](https://github.com/Snazzah/slash-create/blob/66d556cbb5c5b5d3dfa8af9e610709c27e30315c/src/creator.ts#L730), since it assumes its using that same map every command has.

Ah, that's something I didn't spot. Tricky...

Async isn't a problem (the Redis client I use has a sync option!) but it would be beneficial to put it in async for cases like this. I'll see if I can PR it another time!

**Comment by Aericio** [comment]
It could be worth to consider using https://github.com/jaredwray/keyv, so that users can choose which database best fits their needs.

Got currently uses this too, alongside the option of using an in-memory cache. https://github.com/sindresorhus/got/blob/main/documentation/cache.md

**Comment by Snazzah** [comment]
What I will do is fix the problems with the `throttle()` function so it can be extended a lot easier than now. That way, you can use whatever method of throttling if you want, and the library's way of throttling can still work by default.
